### ISSUE TITLE
Add info which folder to use

### ISSUE THREAD

**Issue by alexbaumgertner** [dab/bemup-workshop-vagrant#7]
As `/host/` vagrant directory is linked to `home` host machine, there is a problem when host machine is windows (at least XP) – `npm install` do not work.
![19e1012b93da](https://cloud.githubusercontent.com/assets/223620/4055740/c4b8e87a-2dac-11e4-868a-226f79eb91fb.png)
I tried to create project-stub into `/home/vagrant/` (not `host`) and it worked.
So, when your host machine is Windows, you should not use linked (synced) directory.

**Comment by dab** [comment]
thanks for testing
